import { TokenService } from '@/modules/token/services/token.service'
import { describe, expect, it, vi } from 'vitest'

describe('Token Service', () => {
	it('should call jwtSign with the correct payload', () => {
		const jwtSign = vi.fn().mockReturnValue('fake-token')
		const sut = new TokenService(jwtSign)

		sut.generateToken('user-1')

		expect(jwtSign).toHaveBeenCalledWith({ sub: 'user-1' }, { expiresIn: '1d' })
	})

	it('should return the token generated by jwtSign', () => {
		const jwtSign = vi.fn().mockReturnValue('fake-token')
		const sut = new TokenService(jwtSign)

		const token = sut.generateToken('user-1')

		expect(token).toBe('fake-token')
	})
})
